// <auto-generated />
namespace CoursesManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class sectionsLesonupdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sectionsLesonupdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202309290509025_sections-Leson-updates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
